apiVersion: v1
kind: Secret

metadata:
  name: django-secret
  namespace: clickmart

type: Opaque

stringData:
  SECRET_KEY: test-secret-key
  EMAIL_HOST_USER: test@example
  EMAIL_HOST_PASSWORD: testpassword