apiVersion: v1
kind: Secret 

metadata:
  name: postgres-secret
  namespace: clickmart

type: Opaque

stringData:
  POSTGRES_USER: clickmart
  POSTGRES_PASSWORD: clickmart123
  POSTGRES_DB: clickmart
