sonar.projectKey=clickmart
sonar.projectName=ClickMart

sonar.sources=backend-drf,frontend
sonar.tests=backend-drf

sonar.exclusions=**/venv/**,**/.venv/**,**/__pycache__/**,**/migrations/**,**/node_modules/**,**/static/**,**/staticfiles/**,**/media/**,**/tests.py,**/Dockerfile

sonar.test.inclusions=backend-drf/**/tests.py

sonar.python.coverage.reportPaths=backend-drf/coverage.xml
