sonar.projectKey=clickmart
sonar.projectName=ClickMart
sonar.projectVersion=1.0

sonar.sources=backend-drf,frontend
sonar.tests=backend-drf

sonar.sourceEncoding=UTF-8

sonar.python.version=3.11

sonar.exclusions=**/node_modules/**,**/venv/**,**/.venv/**,**/__pycache__/**,**/dist/**,**/build/**,**/migrations/**,**/static/**,**/staticfiles/**,**/media/**,**/*.min.js

sonar.coverage.exclusions=**/migrations/**,**/tests.py,**/admin.py,**/apps.py,**/manage.py,**/settings.py,**/urls.py

sonar.cpd.exclusions=**/migrations/**

sonar.python.coverage.reportPaths=backend-drf/coverage.xml
