name: Clickmart CD Pipeline
on:
  push:
    branches:
      - main

permissions:
  contents: read

env: 
  DOCKER_BUILDKIT: 1

jobs:
  docker-build:
    name: Build Docker Images

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build Backend
      run: |
        docker build \
          -t clickmart-backend:latest \
          -t clickmart-backend:${{ github.sha }} \
          ./backend-drf

    - name: Build Frontend
      run: |
        docker build \
          -t clickmart-frontend:latest \
          -t clickmart-frontend:${{ github.sha }} \
          ./frontend

  trivy-scan:
    name: Trivy Scan
    needs:
      - docker-build

    runs-on: self-hosted

    steps:
      - name: Check Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: clickmart-backend:latest
          format: table
          exit-code: "0"
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          skip-update: true

      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: clickmart-frontend:latest
          format: table
          exit-code: "0"
          severity: HIGH,CRITICAL
          skip-update: true

  docker-push:
    name: Push Images

    runs-on: self-hosted

    needs: trivy-scan

    steps:

    - uses: actions/checkout@v4

    - name: Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Backend
      run: |
        docker tag clickmart-backend:latest \
        ${{ secrets.DOCKER_USERNAME }}/clickmart-backend:latest

        docker tag clickmart-backend:${{ github.sha }} \
        ${{ secrets.DOCKER_USERNAME }}/clickmart-backend:${{ github.sha }}

    - name: Push Backend
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/clickmart-backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/clickmart-backend:${{ github.sha }}

    - name: Tag Frontend
      run: |
        docker tag clickmart-frontend:latest \
        ${{ secrets.DOCKER_USERNAME }}/clickmart-frontend:latest

        docker tag clickmart-frontend:${{ github.sha }} \
        ${{ secrets.DOCKER_USERNAME }}/clickmart-frontend:${{ github.sha }}

    - name: Push Frontend
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/clickmart-frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/clickmart-frontend:${{ github.sha }}

  kubernetes-deployment: 
      name: Deploy to Kubernetes
      runs-on: self-hosted

      needs: docker-push

      steps: 
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Verify Kubernetes Cluster
          run: |
            kubectl cluster-info
            kubectl get nodes
            kubectl get ns

        - name: Make Script Executable
          run: chmod +x K8s/deploy.sh

        - name: Deploy Application
          run: ./K8s/deploy.sh

        - name: Update Frontend Image
          run: |
            kubectl set image deployment/frontend-deployment \
            frontend=${{ secrets.DOCKER_USERNAME }}/clickmart-frontend:${{ github.sha }} \
            -n clickmart

        - name: Update Backend Image
          run: |
            kubectl set image deployment/backend-deployment \
            backend=${{ secrets.DOCKER_USERNAME }}/clickmart-backend:${{ github.sha }} \
            -n clickmart

        - name: Wait for Backend Rollout
          run: |
            kubectl rollout status deployment/backend-deployment -n clickmart --timeout=180s

        - name: Wait for Frontend Rollout
          run: |
            kubectl rollout status deployment/frontend-deployment -n clickmart --timeout=180s
