name: Clickmart CI/CD Pipeline
on:
  push:
    branches:
      - franklyn
      - main

permissions:
  contents: read

env: 
  DOCKER_BUILDKIT: 1

jobs:
  backend-ci:

    runs-on: self-hosted

    defaults:
      run:
        working-directory: backend-drf

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt

      - name: Run Flake8
        run: flake8 .

      - name: Create CI environment
        run: cp .env.ci .env

      - name: Run Migrations
        run: |
          python manage.py migrate

      - name: Django system check
        run: python manage.py check

      - name: Run Tests
        run: python manage.py test

  frontend-ci:
    
    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Packages
        run: npm ci --prefer-offline --no-audit


  sonar-analysis:
    name: SonarQube Analysis
    needs: 
      - frontend-ci
      - backend-ci
    runs-on: self-hosted

    steps:
      - name: Check Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Verify SonarQube connectivity
        env:
        
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
            echo "Checking SonarQube..."
            curl -v "$SONAR_HOST_URL/api/system/status"

      - name: Sonarqube Scan
        uses: SonarSource/sonarqube-scan-action@v6

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  docker-build:
    name: Build Docker Images
    runs-on: self-hosted

    needs: sonar-analysis

    steps:
    - uses: actions/checkout@v4

    - name: Build Backend
      run: |
        docker build \
          -t clickmart-backend:latest \
          -t clickmart-backend:${{ github.sha }} \
          ./backend-drf

    - name: Build Frontend
      run: |
        docker build \
          -t clickmart-frontend:latest \
          -t clickmart-frontend:${{ github.sha }} \
          ./frontend

  trivy-scan:
    name: Trivy Scan
    needs:
      - docker-build

    runs-on: self-hosted

    steps:
      - name: Check Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: clickmart-backend:latest
          format: table
          exit-code: "0"
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          skip-update: true

      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: clickmart-frontend:latest
          format: table
          exit-code: "0"
          severity: HIGH,CRITICAL
          skip-update: true

  docker-push:
    name: Push Images

    runs-on: self-hosted

    needs: trivy-scan

    steps:

    - uses: actions/checkout@v4

    - name: Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Backend
      run: |
        docker tag clickmart-backend:latest \
        ${{ secrets.DOCKER_USERNAME }}/clickmart-backend:latest

        docker tag clickmart-backend:${{ github.sha }} \
        ${{ secrets.DOCKER_USERNAME }}/clickmart-backend:${{ github.sha }}

    - name: Push Backend
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/clickmart-backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/clickmart-backend:${{ github.sha }}

    - name: Tag Frontend
      run: |
        docker tag clickmart-frontend:latest \
        ${{ secrets.DOCKER_USERNAME }}/clickmart-frontend:latest

        docker tag clickmart-frontend:${{ github.sha }} \
        ${{ secrets.DOCKER_USERNAME }}/clickmart-frontend:${{ github.sha }}

    - name: Push Frontend
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/clickmart-frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/clickmart-frontend:${{ github.sha }}