name: Continuous Integration
on:
  push:
    branches:
      - franklyn

permissions:
  contents: read

jobs:
  backend-ci:

    runs-on: self-hosted

    env:
      DOCKER_BUILDKIT: 1

    defaults:
      run:
        working-directory: backend-drf

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: backend-drf/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt

      - name: Run Flake8
        run: flake8 .

      - name: Create CI environment
        run: cp .env.ci .env

      - name: Run Migrations
        run: |
          python manage.py migrate

      - name: Django system check
        run: python manage.py check

      - name: Run Tests
        run: python manage.py test

      - name: Build Backend Docker Image
        run: |
          docker build \
            --cache-from clickmart-backend:latest \
            -t clickmart-backend:latest .

  frontend-ci:
    
    runs-on: self-hosted
    
    env:
      DOCKER_BUILDKIT: 1

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Packages
        run: npm ci --prefer-offline --no-audit

      - name: Run ESLint
        run: npm run lint

      - name: Build Frontend Docker Image
        run: |
          docker build \
           --cache-from clickmart-frontend:latest \
           -t clickmart-frontend:latest .

  sonar-analysis:
    name: SonarQube Analysis
    needs: 
      - frontend-ci
      - backend-ci
    runs-on: self-hosted

    steps:
      - name: Check Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sonarqube Scan
        uses: SonarSource/sonarqube-scan-action@v5

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  trivy-scan:
    name: Trivy Scan
    needs:
      - frontend-ci
      - backend-ci

    runs-on: self-hosted

    steps:
      - name: Check Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: clickmart-backend:latest
          format: table
          exit-code: "0"
          severity: HIGH,CRITICAL
          ignore-unfixed: true

      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: clickmart-frontend:latest
          format: table
          exit-code: "0"
          severity: HIGH,CRITICAL